apiVersion: v1
kind: Pod
metadata:
  labels:
    run: phpadmin-pod
  name: phpadmin-pod
spec:
  containers:
  - image: phpmyadmin
    name: phpadmin-pod
    ports:
    - containerPort: 80
    envFrom:
    - configMapRef:
        name: phpadmin-cm
    - secretRef:
        name: phpadmin-secret
  dnsPolicy: ClusterFirst
  restartPolicy: Always