apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: phpapp-pod
  name: phpapp-svc
spec:
  ports:
  - port: 8020
    protocol: TCP
    targetPort: 80
  selector:
    run: phpapp-pod
  type: NodePort
status:
  loadBalancer: {}
